export const Allow = () => () => {}
export const IS_DEFINED = () => () => {}
export const IsDefined = () => () => {}
export const IsOptional = () => () => {}
export const ValidatorConstraint = () => () => {}
export const Validate = () => () => {}
export const ValidateBy = () => () => {}
export const ValidateIf = () => () => {}
export const ValidateNested = () => () => {}
export const ValidatePromise = () => () => {}
export const IS_LATLONG = () => () => {}
export const IsLatLong = () => () => {}
export const IS_LATITUDE = () => () => {}
export const IsLatitude = () => () => {}
export const IS_LONGITUDE = () => () => {}
export const IsLongitude = () => () => {}
export const EQUALS = () => () => {}
export const Equals = () => () => {}
export const NOT_EQUALS = () => () => {}
export const NotEquals = () => () => {}
export const IS_EMPTY = () => () => {}
export const IsEmpty = () => () => {}
export const IS_NOT_EMPTY = () => () => {}
export const IsNotEmpty = () => () => {}
export const IS_IN = () => () => {}
export const IsIn = () => () => {}
export const IS_NOT_IN = () => () => {}
export const IsNotIn = () => () => {}
export const IS_DIVISIBLE_BY = () => () => {}
export const IsDivisibleBy = () => () => {}
export const IS_POSITIVE = () => () => {}
export const IsPositive = () => () => {}
export const IS_NEGATIVE = () => () => {}
export const IsNegative = () => () => {}
export const MAX = () => () => {}
export const Max = () => () => {}
export const MIN = () => () => {}
export const Min = () => () => {}
export const MIN_DATE = () => () => {}
export const MinDate = () => () => {}
export const MAX_DATE = () => () => {}
export const MaxDate = () => () => {}
export const CONTAINS = () => () => {}
export const Contains = () => () => {}
export const NOT_CONTAINS = () => () => {}
export const NotContains = () => () => {}
export const IS_ALPHA = () => () => {}
export const IsAlpha = () => () => {}
export const IS_ALPHANUMERIC = () => () => {}
export const IsAlphanumeric = () => () => {}
export const IS_DECIMAL = () => () => {}
export const IsDecimal = () => () => {}
export const IS_ASCII = () => () => {}
export const IsAscii = () => () => {}
export const IS_BASE64 = () => () => {}
export const IsBase64 = () => () => {}
export const IS_BYTE_LENGTH = () => () => {}
export const IsByteLength = () => () => {}
export const IS_CREDIT_CARD = () => () => {}
export const IsCreditCard = () => () => {}
export const IS_CURRENCY = () => () => {}
export const IsCurrency = () => () => {}
export const IS_EMAIL = () => () => {}
export const IsEmail = () => () => {}
export const IS_FQDN = () => () => {}
export const IsFQDN = () => () => {}
export const IS_FULL_WIDTH = () => () => {}
export const IsFullWidth = () => () => {}
export const IS_HALF_WIDTH = () => () => {}
export const IsHalfWidth = () => () => {}
export const IS_VARIABLE_WIDTH = () => () => {}
export const IsVariableWidth = () => () => {}
export const IS_HEX_COLOR = () => () => {}
export const IsHexColor = () => () => {}
export const IS_HEXADECIMAL = () => () => {}
export const IsHexadecimal = () => () => {}
export const IS_MAC_ADDRESS = () => () => {}
export const IsMACAddress = () => () => {}
export const IS_IP = () => () => {}
export const IsIP = () => () => {}
export const IS_PORT = () => () => {}
export const IsPort = () => () => {}
export const IS_ISBN = () => () => {}
export const IsISBN = () => () => {}
export const IS_ISIN = () => () => {}
export const IsISIN = () => () => {}
export const IS_ISO8601 = () => () => {}
export const IsISO8601 = () => () => {}
export const IS_JSON = () => () => {}
export const IsJSON = () => () => {}
export const IS_JWT = () => () => {}
export const IsJWT = () => () => {}
export const IS_LOWERCASE = () => () => {}
export const IsLowercase = () => () => {}
export const IS_MOBILE_PHONE = () => () => {}
export const IsMobilePhone = () => () => {}
export const IS_ISO31661_ALPHA_2 = () => () => {}
export const IsISO31661Alpha2 = () => () => {}
export const IS_ISO31661_ALPHA_3 = () => () => {}
export const IsISO31661Alpha3 = () => () => {}
export const IS_MONGO_ID = () => () => {}
export const IsMongoId = () => () => {}
export const IS_MULTIBYTE = () => () => {}
export const IsMultibyte = () => () => {}
export const IS_SURROGATE_PAIR = () => () => {}
export const IsSurrogatePair = () => () => {}
export const IS_URL = () => () => {}
export const IsUrl = () => () => {}
export const IS_UUID = () => () => {}
export const IsUUID = () => () => {}
export const IS_FIREBASE_PUSH_ID = () => () => {}
export const IsFirebasePushId = () => () => {}
export const IS_UPPERCASE = () => () => {}
export const IsUppercase = () => () => {}
export const IS_LENGTH = () => () => {}
export const Length = () => () => {}
export const MAX_LENGTH = () => () => {}
export const MaxLength = () => () => {}
export const MIN_LENGTH = () => () => {}
export const MinLength = () => () => {}
export const MATCHES = () => () => {}
export const Matches = () => () => {}
export const IS_PHONE_NUMBER = () => () => {}
export const IsPhoneNumber = () => () => {}
export const IS_MILITARY_TIME = () => () => {}
export const IsMilitaryTime = () => () => {}
export const IS_HASH = () => () => {}
export const IsHash = () => () => {}
export const IS_ISSN = () => () => {}
export const IsISSN = () => () => {}
export const IS_DATE_STRING = () => () => {}
export const IsDateString = () => () => {}
export const IS_BOOLEAN_STRING = () => () => {}
export const IsBooleanString = () => () => {}
export const IS_NUMBER_STRING = () => () => {}
export const IsNumberString = () => () => {}
export const IS_BASE32 = () => () => {}
export const IsBase32 = () => () => {}
export const IS_BIC = () => () => {}
export const IsBIC = () => () => {}
export const IS_BTC_ADDRESS = () => () => {}
export const IsBtcAddress = () => () => {}
export const IS_DATA_URI = () => () => {}
export const IsDataURI = () => () => {}
export const IS_EAN = () => () => {}
export const IsEAN = () => () => {}
export const IS_ETHEREUM_ADDRESS = () => () => {}
export const IsEthereumAddress = () => () => {}
export const IS_HSL = () => () => {}
export const IsHSL = () => () => {}
export const IS_IBAN = () => () => {}
export const IsIBAN = () => () => {}
export const IS_IDENTITY_CARD = () => () => {}
export const IsIdentityCard = () => () => {}
export const IS_ISRC = () => () => {}
export const IsISRC = () => () => {}
export const IS_LOCALE = () => () => {}
export const IsLocale = () => () => {}
export const IS_MAGNET_URI = () => () => {}
export const IsMagnetURI = () => () => {}
export const IS_MIME_TYPE = () => () => {}
export const IsMimeType = () => () => {}
export const IS_OCTAL = () => () => {}
export const IsOctal = () => () => {}
export const IS_PASSPORT_NUMBER = () => () => {}
export const IsPassportNumber = () => () => {}
export const IS_POSTAL_CODE = () => () => {}
export const IsPostalCode = () => () => {}
export const IS_RFC_3339 = () => () => {}
export const IsRFC3339 = () => () => {}
export const IS_RGB_COLOR = () => () => {}
export const IsRgbColor = () => () => {}
export const IS_SEM_VER = () => () => {}
export const IsSemVer = () => () => {}
export const IS_STRONG_PASSWORD = () => () => {}
export const IsStrongPassword = () => () => {}
export const IS_TIMEZONE = () => () => {}
export const IsTimeZone = () => () => {}
export const IS_BASE58 = () => () => {}
export const IsBase58 = () => () => {}
export const IS_TAX_ID = () => () => {}
export const IsTaxId = () => () => {}
export const IS_ISO4217_CURRENCY_CODE = () => () => {}
export const IsISO4217CurrencyCode = () => () => {}
export const IS_BOOLEAN = () => () => {}
export const IsBoolean = () => () => {}
export const IS_DATE = () => () => {}
export const IsDate = () => () => {}
export const IS_NUMBER = () => () => {}
export const IsNumber = () => () => {}
export const IS_ENUM = () => () => {}
export const IsEnum = () => () => {}
export const IS_INT = () => () => {}
export const IsInt = () => () => {}
export const IS_STRING = () => () => {}
export const IsString = () => () => {}
export const IS_ARRAY = () => () => {}
export const IsArray = () => () => {}
export const IS_OBJECT = () => () => {}
export const IsObject = () => () => {}
export const ARRAY_CONTAINS = () => () => {}
export const ArrayContains = () => () => {}
export const ARRAY_NOT_CONTAINS = () => () => {}
export const ArrayNotContains = () => () => {}
export const ARRAY_NOT_EMPTY = () => () => {}
export const ArrayNotEmpty = () => () => {}
export const ARRAY_MIN_SIZE = () => () => {}
export const ArrayMinSize = () => () => {}
export const ARRAY_MAX_SIZE = () => () => {}
export const ArrayMaxSize = () => () => {}
export const ARRAY_UNIQUE = () => () => {}
export const ArrayUnique = () => () => {}
export const IS_NOT_EMPTY_OBJECT = () => () => {}
export const IsNotEmptyObject = () => () => {}
export const IS_INSTANCE = () => () => {}
export const IsInstance = () => () => {}
export const ValidationError = () => () => {}
export const ValidationTypes = () => () => {}
export const Validator = () => () => {}
export const MetadataStorage = () => () => {}
export const ClassTransformer = () => () => {}
export const Exclude = () => () => {}
export const Expose = () => () => {}
export const TransformInstanceToInstance = () => () => {}
export const TransformInstanceToPlain = () => () => {}
export const TransformPlainToInstance = () => () => {}
export const Transform = () => () => {}
export const Type = () => () => {}
export const TransformationType = () => () => {}
