-- AlterTable
ALTER TABLE "Application" ALTER COLUMN "isPaid" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Credit" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Refund" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "refundStatus" SET DEFAULT 'PENDING';
